---
apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-cloudflare-updater-secret
type: Opaque
data:
  CF_API_KEY: YOUR_CLOUDFLARE_API_KEY_BASE64_ENCODED
  CF_API_EMAIL: YOUR_CLOUDFLARE_EMAIL_BASE64_ENCODED
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kubernetes-cloudflare-updater
spec:
  template:
    metadata:
      labels:
        app: kubernetes-cloudflare-updater
      name: kubernetes-cloudflare-updater
    spec:
      hostNetwork: true
      containers:
      - image: quay.io/galexrt/kubernetes-cloudflare-updater:latest
        name: kubernetes-cloudflare-updater
        command:
          - /bin/bash
          - -c
          - 'export DNS_NAMES="k8s-masters.example.com,k8s-workers.example.com" IP_ADDRESS="$(ip -o -4 addr list enp3s0 | awk '{print $4}' | cut -d/ -f1),$(ip -o -6 addr list enp3s0 | awk '{print $4}' | cut -d/ -f1)" && exec /bin/kubernetes-cloudflare-updater'
        env:
          - name: CF_API_KEY
            valueFrom:
              secretKeyRef:
                name: kubernetes-cloudflare-updater-secret
                key: CF_API_KEY
          - name: CF_API_EMAIL
            valueFrom:
              secretKeyRef:
                name: kubernetes-cloudflare-updater-secret
                key: CF_API_EMAIL
        resources:
          limits:
            cpu: 150m
            memory: 100Mi
          requests:
            cpu: 150m
            memory: 100Mi
      terminationGracePeriodSeconds: 30
